### ISSUE TITLE
About loss calculation

### ISSUE THREAD

**Issue by Zbozhou** [synsin0/StreamingFlow#1]
Thanks for your great work, I am wondering is this the Auxiliary Loss mentioned in the main paper, and why you set it to 0 here.
https://github.com/synsin0/StreamingFlow/blob/main/streamingflow/layers/temporal_ode_bayes.py#L626

**Comment by synsin0** [comment]
Hi, the pre-jump loss and post-jump loss originates from GRU-ODE-Bayes, which computes the KL divergence between input(after p_model) and X_obs. However, someone tells me that this loss may suppress the new measurements updating to the state, so I try to simplify this update process and gets very similar results in this voxelnet-based implementation, though not very stable. Deletion of auxiliary loss makes it easier to adapt to 4D occupancy settings. So I open-source this simplified version.
